-- V1: 기준선 스키마
-- 2026-09-24 시점 엔티티(Hibernate 6, PostgreSQL)에서 생성한 DDL.
-- 기존 운영 DB는 이 파일을 실행하지 않고 baseline(버전 1)으로만 등록된다 (application-prod.yml 참고).
-- 새 빈 DB(테스트·신규 환경)에서만 실제로 실행된다.

create table member (
    height integer,
    weight integer,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    refresh_token varchar(512),
    birth_date varchar(255),
    email varchar(255) not null unique,
    experience varchar(255),
    goal varchar(255),
    image_url varchar(255),
    nickname varchar(255) not null,
    phone varchar(255),
    provider varchar(255) not null check (provider in ('GOOGLE','KAKAO')),
    provider_id varchar(255) not null,
    role varchar(255) not null check (role in ('USER','ADMIN')),
    primary key (id)
);

create table workout (
    id bigint generated by default as identity,
    member_id bigint,
    workout_part_id bigint not null,
    name varchar(255) not null,
    primary key (id),
    constraint workout_name_part_id_unique unique (name, workout_part_id)
);

create table workout_part (
    id bigint generated by default as identity,
    member_id bigint,
    name varchar(255) not null unique,
    primary key (id)
);

create table workout_program (
    created_at timestamp(6),
    deleted_at timestamp(6),
    id bigint generated by default as identity,
    member_id bigint,
    updated_at timestamp(6),
    description varchar(255),
    name varchar(255) not null,
    primary key (id)
);

create table workout_program_exercise (
    orders integer,
    id bigint generated by default as identity,
    workout_id bigint not null,
    workout_program_part_id bigint,
    primary key (id)
);

create table workout_program_part (
    orders integer,
    id bigint generated by default as identity,
    workout_part_id bigint not null,
    workout_program_id bigint,
    primary key (id)
);

create table workout_program_set (
    reps integer,
    rest_time integer,
    set_number integer,
    weight float(53),
    id bigint generated by default as identity,
    workout_program_exercise_id bigint,
    memo varchar(255),
    primary key (id)
);

create table workout_session (
    created_at timestamp(6),
    end_time timestamp(6) with time zone,
    id bigint generated by default as identity,
    last_paused_at timestamp(6) with time zone,
    member_id bigint,
    start_time timestamp(6) with time zone,
    total_paused_seconds bigint,
    updated_at timestamp(6),
    workout_program_id bigint,
    status varchar(255) check (status in ('IN_PROGRESS','PAUSED','COMPLETED','CANCELLED')),
    primary key (id)
);

create table workout_session_exercise (
    "order" integer,
    skipped boolean default false not null,
    id bigint generated by default as identity,
    started_at timestamp(6) with time zone,
    workout_id bigint,
    workout_session_id bigint,
    primary key (id)
);

create table workout_session_set (
    actual_reps integer,
    actual_weight float(53),
    completed boolean,
    reps integer,
    rest_time integer,
    set_number integer,
    weight float(53),
    completed_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    workout_session_exercise_id bigint,
    actual_memo varchar(255),
    memo varchar(255),
    primary key (id)
);

alter table if exists workout
   add constraint FKjw2b7cejitb4sfno8yi21p98l
   foreign key (member_id)
   references member;

alter table if exists workout
   add constraint FKkgb8w3fmftmqbd2qrl7d4lwsy
   foreign key (workout_part_id)
   references workout_part;

alter table if exists workout_part
   add constraint FKsaas8l7urgktyjklk3r2it5ne
   foreign key (member_id)
   references member;

alter table if exists workout_program
   add constraint FKr3erbnwtnlr6vgbvttyr3d1h8
   foreign key (member_id)
   references member;

alter table if exists workout_program_exercise
   add constraint FKfrm2nq08wxs5o05txbngme65x
   foreign key (workout_id)
   references workout;

alter table if exists workout_program_exercise
   add constraint FKpp3hejyfwhy2vd6lpfibnafs1
   foreign key (workout_program_part_id)
   references workout_program_part;

alter table if exists workout_program_part
   add constraint FKfkd5iuw3jpfo1jcnchfx0q2fq
   foreign key (workout_part_id)
   references workout_part;

alter table if exists workout_program_part
   add constraint FKl6190k7k0nmr7um0kh6aqppn8
   foreign key (workout_program_id)
   references workout_program;

alter table if exists workout_program_set
   add constraint FK6ilbee11gs0fdd0e09luwo9so
   foreign key (workout_program_exercise_id)
   references workout_program_exercise;

alter table if exists workout_session
   add constraint FKfdsficgj0dqvxvqv6ruel6mrh
   foreign key (member_id)
   references member;

alter table if exists workout_session
   add constraint FKbtydk8ay21danx50fd7arca5
   foreign key (workout_program_id)
   references workout_program;

alter table if exists workout_session_exercise
   add constraint FK91gsinhqx2dkb65j2ymnwpht5
   foreign key (workout_id)
   references workout;

alter table if exists workout_session_exercise
   add constraint FKqi3wn9ba0iuqifl39e3mt23ix
   foreign key (workout_session_id)
   references workout_session;

alter table if exists workout_session_set
   add constraint FKhe7d45gc8cr0qkvwsccqo7ead
   foreign key (workout_session_exercise_id)
   references workout_session_exercise;
