-- V4: 인증 재설계 (#3, #4, #5, #25)
-- 주의: 배포 시점에 기존 로그인 상태는 모두 만료된다 (사용자 1회 재로그인).

-- 1) OAuth 계정은 이메일이 아니라 (provider, provider_id) 로 식별한다
--    기존 데이터에 중복이 있으면 이 문장이 실패하고 배포가 중단된다 (배포 전 중복 조회 필요).
ALTER TABLE member
    ADD CONSTRAINT uk_member_provider_provider_id UNIQUE (provider, provider_id);

-- 2) 로그인 세션: 기기(로그인)마다 1행. Refresh 토큰은 SHA-256 해시만 저장한다.
--    previous_token_hash 는 회전 직전 토큰으로, 재사용(탈취 의심) 감지에 사용한다.
CREATE TABLE auth_session (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           bigint       NOT NULL REFERENCES member (id),
    refresh_token_hash  varchar(64)  NOT NULL UNIQUE,
    previous_token_hash varchar(64),
    created_at          timestamptz  NOT NULL DEFAULT now(),
    last_used_at        timestamptz  NOT NULL DEFAULT now(),
    rotated_at          timestamptz,
    expires_at          timestamptz  NOT NULL,
    revoked_at          timestamptz
);
CREATE INDEX ix_auth_session_member ON auth_session (member_id);
CREATE INDEX ix_auth_session_previous_hash ON auth_session (previous_token_hash);

-- 3) OAuth 로그인 성공 후 프론트로 전달하는 일회용 교환 코드 (URL에 토큰을 싣지 않기 위함)
CREATE TABLE auth_login_code (
    code_hash  varchar(64) PRIMARY KEY,
    member_id  bigint      NOT NULL REFERENCES member (id),
    expires_at timestamptz NOT NULL
);

-- 4) OAuth2 인가 요청(state) 저장소: 인스턴스 메모리 세션 대신 DB에 저장 (다중 인스턴스/재시작 대응)
CREATE TABLE oauth2_authorization_request (
    state      varchar(255) PRIMARY KEY,
    payload    bytea        NOT NULL,
    expires_at timestamptz  NOT NULL
);

-- 5) 회원당 1개였던 Refresh 토큰 컬럼 제거 (auth_session 으로 대체)
ALTER TABLE member DROP COLUMN refresh_token;
